### ISSUE TITLE
Wrong mechanism for creating subscription specific FlowControlSettings in GcpPubSubAutoConfiguration

### ISSUE THREAD

**Issue by bohdanowicz** [GoogleCloudPlatform/spring-cloud-gcp#1005]
In class `GcpPubSubAutoConfiguration` in method `createAndRegisterSelectiveFlowControlSettings` you are iterating over entries in subscriber map:
`for (Map.Entry<String, PubSubConfiguration.Subscriber> subscription :
        subscriberMap.entrySet())`
The issue here is that within this loop you are also calling:
``` 
this.gcpPubSubProperties.computeSubscriberFlowControlSettings(subscriptionName, this.finalProjectIdProvider.getProjectId());
```
Which underneath executes method `getSubscriber` from class `com.google.cloud.spring.pubsub.core.PubSubConfiguration` which internally modifies entry set over which you are iterating (one mentioned above). Code responsible for that:
```if (this.subscription.containsKey(subscriptionName)
        && projectIdFromFullName.equals(projectId)) {
      this.subscription.putIfAbsent(
          fullyQualifiedSubscriptionKey, this.subscription.get(subscriptionName));
      this.subscription.remove(subscriptionName);
      return this.subscription.get(fullyQualifiedSubscriptionKey);
    }
```
Obviously such a modification of a set should be illegal since there is no guarantee in the order of processing elements. Such a situation leads to errors like `BeanDefinitionOverrideException` - if subscriber is processed twice during iteration.

**Comment by elefeint** [comment]
@mpeddada1 Could you take a look?

**Comment by mpeddada1** [comment]
Hi @bohdanowicz, thanks for bringing this up. Please allow me to reiterate the problem statement to make sure that I understood the situation accurately. So this block of code ensures that we store fully qualified names instead of a subscription names to reduce the likelihood of subscription names with different project ids clashing with each other. However, in the process of doing that, we are editing `this.subscription` in `PubSubConfiguration`  while iterating over it in `GcpPubSubAutoconfiguration`. 

Maybe a better approach would be to store the fully qualified names and associated subscribers in a new map instead of modifying the existing map? This will increase the # things we need to store but reduce potential conflicts in the future. What do you think @elefeint?

**Comment by elefeint** [comment]
@mpeddada1 yes; it would be safest to treat all `@ConfigurationProperties` as immutable. One way to make this safer would be to allow only `getSubscriptionKeys()` instead of `getSubscription()`. Another way would be, like you said, to return a different map with pre-calculated fully qualified keys.

I am also separately curious about the issue @bohdanowicz mentioned of not being able to use fully-qualified names -- this sounds like a separate issue we should address. `registerSelectiveSchedulerBeans()` should not assume it's passed short names.

**Comment by elefeint** [comment]
Sorry, missed the question. Allowing bean overriding would have worked. 
The upcoming release should have this issue resolved, plus support fully-qualified subscription names.

**Comment by poznachowski** [comment]
@elefeint are you able to provide ETA for next release?

**Comment by elefeint** [comment]
Spring Cloud GCP 3.3.0 is out and has this fix.
