### ISSUE TITLE
fetch new secrets by spring-cloud-gcp-secretmanager after secrets updated in google-secret-manager.

### ISSUE THREAD

**Issue by gaurav517** [GoogleCloudPlatform/spring-cloud-gcp#1184]
Can `spring-cloud-gcp-secretmanager` fetch secrets in real time if a secret is changed? Or, secrets are only fetched during application start?
If it can fetch real time secrets update, then how is the cache configured? e.g. in case of a network issue etc., apps would continue to use values from cache?
Thanks.

**Comment by zhumin8** [comment]
Our integration provides two ways of accessing secrets, if you use Secret Manager as a bootstrap property source, then secrets are loaded as properties into application context at application start, you can read more in [this doc section](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#secret-manager-property-source). 
We also provide `SecretManagerTemplate` class that allows operations of creating, updating and reading secrets, read more [here](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#secret-manager-template).
Also, refer to this [sample application](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample) that showcases these usages.

**Comment by elefeint** [comment]
Let's test out how Secret Manager works with `@RefreshScope` nowadays. It is likely that we still have the issue spring-attic/spring-cloud-gcp#2485, since we never implemented the approach in #149.

@JoeWang1127 Take a look at the Secret Manager sample, and try to make it work with [`@RefreshScope`](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#refresh-scope). This will likely lead us to implementing #149.

**Comment by JoeWang1127** [comment]
I found a workaround while we are implementing #149 in [here](https://github.com/JoeWang1127/refreshable-secret-manager).
You can also integrate GCP pub/sub to refresh the secret automatically when a new version of secret is created, please check the docs [here](https://cloud.google.com/secret-manager/docs/event-notifications?_ga=2.178977190.-383158756.1656435995).

**Comment by dzou** [comment]
> I found a workaround while we are implementing #149 in [here](https://github.com/JoeWang1127/refreshable-secret-manager). You can also integrate GCP pub/sub to refresh the secret automatically when a new version of secret is created, please check the docs [here](https://cloud.google.com/secret-manager/docs/event-notifications?_ga=2.178977190.-383158756.1656435995).

Wow! Nice one @JoeWang1127.

Fyi @elefeint -- Following up on our convo earlier, I originally thought we had to support `spring.config.import` in order to have refreshable secrets. And I think that's what we were discussing about that ConfigProperty that I deleted. Looks like Joe found a great solution tho!

**Comment by elefeint** [comment]
Yeah, it's a great workaround when you have a reasonable number of secrets, but if you have hundreds, having `@RefreshScope` configuration properties is more scalable. So ideally, we should make it work.

It's also been a couple of Spring Cloud versions already since bootstrap method became legacy. We need to switch to supporting config.import before the legacy way becomes legend...

**Comment by JoeWang1127** [comment]
Solved in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1204
