### ISSUE TITLE
Inconsistent spring-cloud-gcp-dependency BOM

### ISSUE THREAD

**Issue by MPLockdown** [GoogleCloudPlatform/spring-cloud-gcp#1291]
**Describe the bug**
I was struggling to enable dependency management in gradle project for my client.
As an example - this did not worked ( sample part from build.gradle):
```
ext {
    springCloudGcpDependenciesVersion = "3.3.0"
    springCloudDependenciesVersion = "2021.0.3"
    springCloudGCPVersion = "1.2.8.RELEASE"
}

dependencies {

//    GCP Cloud
    implementation "org.springframework.cloud:spring-cloud-gcp-starter-sql-postgresql"
    implementation "org.springframework.cloud:spring-cloud-gcp-starter-pubsub"
    implementation "org.springframework.cloud:spring-cloud-gcp-starter-logging"

}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudDependenciesVersion}"
        mavenBom "com.google.cloud:spring-cloud-gcp-dependencies:${springCloudGcpDependenciesVersion}"
    }
}
```

I had to plainly use version for each `implementation` statement in `build.gradle`. Simply dependency management bom `com.google.cloud:spring-cloud-gcp-dependencies` did not provides `org.springframework.cloud` artifacts.
I was tempting to give a blame to build tool but I've looked at maven repository and artifact coordinates:
see **https://mvnrepository.com/artifact/com.google.cloud/spring-cloud-gcp-dependencies/3.3.0**
They do not contain any spring-gcp integrations except some for cloud functions. So this is not a gradle to blame.

But In spring site **https://spring.io/projects/spring-cloud-gcp** you have plainly added that BOM `com.google.cloud` has coordinates to `org.springframework.cloud` group with all the goodies like pubsub, logging, cloudSQL etc.. each of spring user may want to use to integrate to GCP in one ecosystem.

-IMHO either Spring documentation has to be fixed or maven repository double-checked why major part of gcp functionality to spring is ommited?

One more thing - I do not know if I may ask this here but- legit spring framework support BOM `org.springframework.cloud:spring-cloud-gcp-dependencies` is long time not updated while GCP are far away with versions (in my case pubsub-emulator support and secret manager support does not work with such project setup (sample part from build.gradle):
```
plugins {
    id 'org.springframework.boot' version '2.6.9'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
    id 'groovy'
}
```

It looks like this spring BOM is forgotten do be updated while GCP functionalities are in growth spree?

This creates some struggle to users whether they have to decide between:
`org.springframework.cloud:spring-cloud-gcp-dependencies`  with spring support, but some gcp api outdated
and 
`com.google.cloud:spring-cloud-gcp-dependencies` which is better preserved and has api to utilize GCP features in details.

As an example I've encountered that functionalities:
- setting message Retention duration from the Topic side 
```
 return Topic.newBuilder()
                .setName(topicName.toString())
                .setMessageRetentionDuration(
                        Durations.fromSeconds(
                                Long.parseLong(
                                        UtilityParser.fromSpEL(props.getResources().getPubsub().getTopic().retentionDurationSeconds())
                                )
                        )
                )
                .setMessageStoragePolicy(messageStoragePolicy)
                .build();
```
- google `SubscriptionName` object
```
return props.getResources().getPubsub().getSubscriptions().stream()
                .filter(SubscriptionProperties::enabled)
                .map(subProps -> Subscription.newBuilder()
                        .setName(SubscriptionName.of(props.getProjectId(), subProps.id()).toString())
                        .setTopic(topicFQname.toString())
                        .setAckDeadlineSeconds(subProps.ackDeadlineSeconds())
                        .setPushConfig(
                                subProps.pushEndpoint() == null ?
                                        PushConfig.getDefaultInstance() :
                                        PushConfig.newBuilder().setPushEndpoint(subProps.pushEndpoint()).build())
                        .build())
                .toList();
```

both of which are of the same artifact group `import com.google.pubsub.v1.*;` for both mentioned bill of materials,
are not available when using only `org.springframework.cloud:spring-cloud-gcp-dependencies`.

**Comment by elefeint** [comment]
```
  springCloudGcpDependenciesVersion = "3.3.0"
  ...
  springCloudGCPVersion = "1.2.8.RELEASE"
 ```

These two lines are in conflict -- version 1.2.x is very old and [unsupported](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/SECURITY.md). There is no way it would be compatible with other dependencies at the modern version 3.3.0 -- package names have changed between 1.x and 2.x.

Spring Cloud GCP BOM (`spring-cloud-gcp-dependencies`) [manages versions](https://repo.maven.apache.org/maven2/com/google/cloud/spring-cloud-gcp-dependencies/3.3.0/spring-cloud-gcp-dependencies-3.3.0.pom) for all modules released from this repository, plus the Google Cloud client libraries and their dependencies.

`org.springframework.cloud:*` on https://spring.io/projects/spring-cloud-gcp is an oversight -- maven group changed to `com.google.cloud` as of version 2.0.0; we'll fix that -- thank you for catching it.

Spring Cloud GCP left the `spring-cloud` organization as of version 2.0.0 (which is why all the maven group IDs changed from `org.springframework.cloud` to `com.google.cloud`, and package names changed from `org.springframework.cloud.gcp` to `com.google.cloud.spring`. Spring Cloud's announcement is [here](https://spring.io/blog/2020/04/17/spring-cloud-2020-0-0-m1-released).  The migration guide showing what changed when the project switched organizations is [here](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#migration-guide-from-spring-cloud-gcp-1-x-to-2-x).

One more thing that may be helpful is that [Spring Initialzr generates the "ideal" gradle structure](https://start.spring.io/#!type=gradle-project&language=java&platformVersion=2.6.12&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=cloud-gcp) if you add GCP support as a dependency (just note that it won't generate for Spring Boot 2.7 until our next release).
