### ISSUE TITLE
Add Native Image Support in Spring Framework on Google Cloud

### ISSUE THREAD

**Issue by mpeddada1** [GoogleCloudPlatform/spring-cloud-gcp#1565]
While Spring Framework on Google Cloud 4.x adds compatibility for Spring Boot 3.0, we don't currently have support for native image compilation. This issue serves as an umbrella tracker to report on the status of this support in the repository. 
Related Issues:
- https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1559 
- https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1279

**Comment by filipenfst** [comment]
Is there any plans or timelines for you guys to work on this ticket?

**Comment by cpoyatos1** [comment]
+1

**Comment by Tera** [comment]
+1

**Comment by rkettelerij** [comment]
Would be nice wrt cloud run / cloud functions

**Comment by gomezmejiam** [comment]
stuck in this issue, we where making a work around using the gcp rest api via feign but it´s a lot of work and future manteniance

**Comment by MusikPolice** [comment]
+1

**Comment by lgrousset** [comment]
+1

**Comment by jainsahab** [comment]
Hi everyone,

Thanks for showing interest in this feature.

We are targeting this to be finished by the end of April(tentatively) this year.

**Comment by jainsahab** [comment]
Hi everyone,

Thanks for showing interest in this feature.

we are planning to take up this work soon and will keep you updated about the progress.

**Comment by laurent-grousset** [comment]
Native compilation worked fine with Spring Boot 3 and spring-cloud-gcp-dependencies 3.4.0

**Comment by jleonar** [comment]
> Native compilation worked fine with Spring Boot 3 and spring-cloud-gcp-dependencies 3.4.0

It doesn't with the latest version at spring-cloud-gcp-dependencies 4.1.1

**Comment by laurent-grousset** [comment]
@jainsahab moreover, Native Compilation is all the more important as it allows us to mitigate the cold start of Cloud Run running Spring Boot (this is my case)

**Comment by mat-613** [comment]
+1

**Comment by lutics** [comment]
any update on here?

**Comment by dangazineu** [comment]
Thank you for the interest. We don't have an ETA on this feature yet.

**Comment by pkutlunin** [comment]
I think I found the reason why in versions 4.x.x it stopped working - it's related to #1287 (upgrade to Spring boot 3.0.0).
As it was mentioned in #1559, the code no longer gets compiled with `-parameters` argument. If we take a look at the current version of maven-compiler-plugin, we'll see that the configuration is invalid:
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/4a1d4ecfc3002b865e1692715c1dd4febb10c544/pom.xml#L523

Because of the wrong artifact id, the configuration cannot be applied.
The fix should be easy:
```
<artifactId>maven-compiler-plugin</artifactId>
<version>${maven-compiler-plugin.version}</version>
```

Unfortunately, I couldn't make it work because of errorprone plugin configuration:
> Compilation failure
[ERROR] error: invalid flag: -Xep:UnicodeInCode:OFF

If I remove these 2 flags, the project builds fine:
```
-Xep:UnicodeInCode:OFF \
-Xep:CanIgnoreReturnValue:OFF
```

Could you try if it works for you with the fix? Maybe it's just my local setup that causes issues with errorprone.

**Comment by zhumin8** [comment]
We do not plan to support Native Image in Spring Framework on Google Cloud 4.x. Initial Native Image support is available in Spring Framework on Google Cloud 5.x.
