### ISSUE TITLE
Generate Spring Configuration Metadata via spring-boot-configuration-processor

### ISSUE THREAD

**Issue by mmoayyed** [GoogleCloudPlatform/spring-cloud-gcp#1842]
**Is your feature request related to a problem? Please describe.**

It looks as though the project here does have a dependency on `spring-boot-configuration-processor`, but I don't see the generated JSON in `META-INF/spring-configuration-metadata.json`. I would expect this file to show up in the final JAR for `com.google.cloud:spring-cloud-gcp-autoconfigure:4.3.0` but there exists none.

**Describe the solution you'd like**

There should be a `META-INF/spring-configuration-metadata.json` generated for the  `com.google.cloud:spring-cloud-gcp-autoconfigure`  artifact and released.

**Describe alternatives you've considered**

N/A

**Additional context**

Using google cloud SDK `4.3.0`.

**Comment by mpeddada1** [comment]
@mmoayyed Thanks for filing this issue! To gain a little more info, do you observe the same in the previous versions of spring-cloud-gcp-autoconfigure? Or is this a recent phenomenon that has started happening with `4.3.0`.

**Comment by mmoayyed** [comment]
If I look at history:

- 4.3.0 has the same issue
- 4.2.0 has the same issue
- 4.1.0 has the same issue
- 4.0.0 does NOT have this issue

So somewhere between 4.0.0 and 4.1.0, this capability disappeared.

**Comment by mpeddada1** [comment]
Thanks for the  investigation! A few notes as we look into this further:
I just did a quick verification using `jar -xf` for the `spring-cloud-gcp-autoconfigure` JARs downloaded from Maven Central for versions `4.3.0`,`4.2.0` and `4.1.0` and the `META-INF/spring-configuration-metadata.json` file seems to have been present until `4.3.0`:

<img width="603" alt="Screenshot 2023-05-12 at 1 18 17 PM" src="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/66699525/1958c418-e21e-42a8-bdae-1f1ec32cc108">

**Comment by mmoayyed** [comment]
Thank you, this also confirms what I am seeing in my build as well. (I mistakenly was looking for the file in previous versions under the `spring` directory, sorry about that!).

**Comment by emmileaf** [comment]
Thanks @mpeddada1 for the investigation! 

Since this file [gets generated at compile time](https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html), I checked for it under `spring-cloud-gcp-autoconfigure/target` with `mvn clean install` at a couple of commits, and think it disappeared after https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1775 fixed the `maven-compiler-plugin` artifact id. 

The difference is likely from now needing to specify `spring-boot-configuration-processor` [explicitly](https://stackoverflow.com/a/64031211) under `annotationProcessorPaths`- it was included previously because the plugin was not correctly applying the other configurations.

**Comment by meltsufin** [comment]
@mpeddada1 @emmileaf Sorry for mistakenly closing the issue previously, and thanks for resolving it quickly!
