### ISSUE TITLE
upgrade dependencies in regard to documentation creation

### ISSUE THREAD

**Issue by zhumin8** [GoogleCloudPlatform/spring-cloud-gcp#1909]
**Issue:**
[docCheck](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/.github/workflows/unitTests.yaml#L133-L143) step in release check for Unit Test CI are using outdated dependencies that are fetched from `repo.spring.io`. 
Recent change in `repo.spring.io` does not allow anonymous access to this repository starting [May 25, 2023](https://status.spring.io/incidents/rl38k61jk6hr?u=dlh63rhg824z). (original [notice](https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023) of change)
It's advised to use newer versions of the affected dependencies and fetch from maven central. These dependencies are transitive and possibly affect documentation published. Another possibility is to exclude these dependencies if possible.
A temporary fix (#1907) is in place, refer to its description for more details.

**Comment by emmileaf** [comment]
Thanks @zhumin8 for the investigation and patch to unblock! 

There was only one inherited dependency that needed overriding together with upgrading to spring-cloud-build 4.0.3, so I took a stab at this in #1909, if this looks like a feasible approach to take.

Piggybacking on this issue with a couple of curiosities: 
1. In terms of backporting 1909's fix to the 3.x branch (since it involves upgrading to a 4.x Spring Cloud dependency), would we still need a workaround on v3.1.7 like in #1907?
2. Is the reason why the docs pom inherits from `spring-cloud-build` remnant from when Spring Cloud GCP used to publish refdocs to [spring.io](http://spring.io/)? (Curious if this is something that we could move away from, as a longer term solution)

**Comment by zhumin8** [comment]
@emmileaf On your 2nd point, I did not get to the bottom of it, my superficial understanding is that the inherits has to do with the documentation style renderings. So yes, we have it because we used to publish docs to spring.io, but it's also to render our documentation as it is now. As to move away from, I am all for it, but let's discuss internally.
