### ISSUE TITLE
Unable to Specify Default value with Secret Manager

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/spring-cloud-gcp#213]
See: https://github.com/spring-cloud/spring-cloud-gcp/issues/2444

**Comment by dzou** [comment]
I think it's possible to have default values already using something like this:

```
spring.password=${FOOBAR:${sm://application-secret/latest}}
```

This uses the `:` syntax in SPEL which will evaluate the expression on the left first, and then if it's null it will attempt to evaluate the expression on the right.

Let me do some further testing, will document it if satisfactory.

**Comment by dzou** [comment]
Reopening for user:

![image](https://user-images.githubusercontent.com/3209274/108106653-3bf2c480-705c-11eb-9f9a-a29450cad610.png)

I think it was incorrect for us to assume that a secret not existing should always fail given what the user is saying here; some environments may not require a secret. So we should come up with a proper way of supporting this.

**Comment by elefeint** [comment]
Perhaps as a new flag `spring.cloud.gcp.secretmanager.fail-if-absent` or similar. It would be true by default, keeping the current behavior. But if set to false, it will result in empty string being returned.

**Comment by dzou** [comment]
Sorry, looking back at this discussion, this stems from a design mistake 😢  --

I made the mistake of putting the "colon" into our syntax, thinking that it would be like a URI. However, Spring properties also use `:` to indicate default values too. So for example,

This means we'll default to "default" if ENV_VAR_1 is not provided.

```
my.property.here = ${ENV_VAR_1 : "default"}
```

However, the `sm://` syntax kind of messes up the colon default operator. It treats the first `:` it sees as the "default" operator value. So the below actually will default to the string `"//mySecretId"`.

```
my.property.here = ${sm://mySecretId : "default"}
```

When I wrote the Quarkus secret manager extension, we ended up to omit the `:` to hopefully keep the default colon operator alive: https://quarkiverse.github.io/quarkiverse-docs/quarkus-google-cloud-services/main/secretmanager.html#_reading_secrets_as_properties

```
# 1. Long form - specify the project ID, secret ID, and version
${sm//projects/<project-id>/secrets/<secret-id>/versions/<version-id>}

# 2. Long form - specify project ID, secret ID, and use latest version
${sm//projects/<project-id>/secrets/<secret-id>}

# 3. Short form - specify project ID, secret ID, and version
${sm//<project-id>/<secret-id>/<version-id>}
```

Sorry pals, this is an annoying fix. Maybe it's time to implement this to also support `sm//` in order to enable default values. So just leave `sm://` for legacy purposes, then introduce `sm//` and you can support default values I think...

**Comment by elefeint** [comment]
Hmm. `sm://` was not an unreasonable choice for narrowing the list of properties for which the Secrets Manager backend is accessed, but I guess for application portability it's better to have secret-backend agnostic property names...

The switch to `sm://` was tied with the property source becoming not-enumerable. Arguably, we should switch from extending `EnumerablePropertySource` to extending `PropertySource` directly. Alternatively, we could go back to reading all secrets at startup (which will make a specific prefix less necessary). This is what the initial implementation did. The problem was that SecretManager could contain secrets for all kinds of purposes in the same project, so we switched to using a prefix to indicate which properties were meant to be retrieved from SM. An alternative approach we have not tried before was to "load all" by default, and to provide an array property for "list of valid SM properties", which the SM property source could take advantage of. Or go back to @dzou's original approach of user-specified prefix for properties.

**Comment by JoeWang1127** [comment]
Just want to be more clear, what's wrong about `${${application.secret} : DEFAULT_VALUE}`?

**Comment by elefeint** [comment]
@JoeWang1127 Would `application.secret` be an intermediate variable pointing to `sm://actual-secret`? I think there was also a problem where if `sm://actual-secret` did not exist, we threw an exception -- could you check what happens?

**Comment by JoeWang1127** [comment]
I did some research on the sample [secret manager project](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample).

- `${application.secret:DEFAULT}` will be resolved to a secret value if `application.secret` is a valid property (i.e., a property `application.secret=${sm://application-secret}` exists in property file); otherwise it will be resolved as `DEFAULT`.
- `${${sm://application-secret}:DEFAULT}` will ALWAYS be resolved as `DEFAULT` regardless of `sm://application-secret` exists in Secret Manager or not, this is because `${sm://application-secret}` will be resolved to a secret value first (e.g., Hello world) and Spring will try to resolved `${Hello world:DEFAULT}` and since there is no property called `Hello world`, `DEFAULT` will be returned.

**Comment by elefeint** [comment]
Right, but what happens if `sm://application-secret` does not exist in Secret Manager?
