### ISSUE TITLE
DataStore Repository Bean findByPropertyId is searching in the default Database instead of a custom Database set in the properties.

### ISSUE THREAD

**Issue by amechineni** [GoogleCloudPlatform/spring-cloud-gcp#2610]
As mentioned in the Title, receiving an exception when try to find an entity by Id, Below are the setup details
Multiple Databases created in one project Id, New Database created in datastore mode and the default database is in native mode as is. Currently trying to fetch the data from new database datastore mode. 

Spring properties such as project-id and database-id are being used and the Repository bean picks them correctly as save is currently working as expected like its persisting at the correct Kind in new database. 

springCloudGCPVersion: _4.9.2_ (tried multiple other versions) 

Exception message when fetching: `The request was for database 'projects/project-id/databases/new-database-name' but was attempting to access database 'projects/project-id/databases/(default)'`

**Comment by zhumin8** [comment]
Apologies for the late reply.

I tried to reproduce this with our sample code but failed. It's a bit unclear to me if by "find an entity by Id"/"findByPropertyId" you mean the `findById()` provided by Spring `CrudRepository`,  or a query by convention on a field named "PropertyId"?
In my attempt to reproduce, both works as expected (uploaded to [this branch](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/6ba6acbb1334e3bf68679936659bcfe76035a9bd/spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-basic-sample/src/main/java/com/example/BookController.java#L59-L68)).

Can you provide a reproducer if this issue is still persisting for you?

**Comment by meltsufin** [comment]
Closing as not reproducible. Please re-open if able to reproduce and provide the sample code.
