### ISSUE TITLE
Gradle usage of GCP Spring cloud function -> spring-cloud-function-adapter-gcp

### ISSUE THREAD

**Issue by vijaysdey88** [GoogleCloudPlatform/spring-cloud-gcp#445]
**Is your feature request related to a problem? Please describe.**
Trying to build a gradle project using spring-cloud-function-adapter-gcp for [background fn](https://cloud.spring.io/spring-cloud-function/reference/html/gcp.html) does not work. We tried to convert the maven based sample given [here](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-gcp-background) to gradle, but it fails to generate the wrapper (GcfJarLauncher) for GCF.

**Describe the solution you'd like**
Could you please create a plugin for gradle that can be used out of box.
Alternatively, if there is a way to use existing spring-cloud-function-adapter-gcp for Gradle build, then could you please provide a sample for the same [similar to this one](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-gcp-background).

**Comment by dzou** [comment]
I'll try to find a solution for this.

**Comment by dzou** [comment]
Unfortunately I think this is not possible right now to do with Gradle.

The issue seems to be that we created a [custom JAR Layout for GCF](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-adapters/spring-cloud-function-adapter-gcp/src/main/java/org/springframework/cloud/function/adapter/gcp/layout/GcfJarLayout.java) so that the JARs can be run on GCF. And we are able to override the default JAR Layout by using this configuration in Maven:

```
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<outputDirectory>target/deploy</outputDirectory>
	</configuration>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-adapter-gcp</artifactId>
		</dependency>
	</dependencies>
</plugin>
```

However, it doesn't look like there's a way to do the same thing in Gradle. Studying the Spring Boot Thin Jar Layout, it looks like we would need to write a Gradle plugin similar to what is done here: https://github.com/spring-projects-experimental/spring-boot-thin-launcher#getting-started

Unfortunately I don't think implementing this plugin is the right solution. We need to implement a way for GCF to be able to run Spring Boot JARs -- instead of having to implement a lot changes to our JAR so it can run on GCF. We have some ideas for how to do this but don't have an immediate solution right now.

As a workaround, I would suggest trying to directly deploy containerized Spring Cloud Function apps to [Cloud Run](https://cloud.google.com/run)

**Comment by dzou** [comment]
Sorry, we unfortunately don't have plans to create a solution for Gradle in the immediate future.

Maybe @meltsufin can give some opinions/comments on our objectives here.

**Comment by meltsufin** [comment]
@vijaysdey88 As this is an open source project, I would strongly encourage anyone with a passion for it to try to contribute such a thing. 😉

**Comment by meltsufin** [comment]
Also, I think this discussion is best to be continued on spring-cloud-function repo, where there is [a similar issue](https://github.com/spring-cloud/spring-cloud-function/issues/561). Also this one is probably related: https://github.com/spring-cloud/spring-cloud-function/issues/665.

**Comment by wwadge** [comment]
Workaround: https://github.com/spring-cloud/spring-cloud-function/issues/561#issuecomment-1597482770
