### ISSUE TITLE
Facilitate Spanner client timeout configuration

### ISSUE THREAD

**Issue by joshrai** [GoogleCloudPlatform/spring-cloud-gcp#480]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to configure timeout and retry settings for the Spanner client, per [Google's guidance to use `SpannerOptions`](https://cloud.google.com/spanner/docs/custom-timeout-and-retry#java). At the same time, I'd like to continue leveraging the auto-configuration of the core `SpannerOptions` properties (projectId, credentials, numRpcChannels, SessionPoolOptions, etc.) that's done in `spring-cloud-gcp-autoconfigure`, in [`GcpSpannerAutoConfiguration`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/366b3d9530efda9b9b1e7dcd92d0284a38034c25/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/GcpSpannerAutoConfiguration.java#L124-L170). There might be some Spring configuration trick to do this, but I'm not aware of it.

I'm using version `1.2.5.RELEASE` (`org.springframework.cloud:spring-cloud-gcp-starter-data-spanner:1.2.5.RELEASE`), but it looks like https://github.com/spring-cloud/spring-cloud-gcp (for v1) isn't taking feature requests anymore, and this still seems to be relevant here in the v2 releases.

**Describe the solution you'd like**

I'd like to be able to configure timeout settings (particularly for `ExecuteSqlRequest`s), which to my knowledge is done by having access to a `SpannerOptions` builder; but I'd also like the `SpannerOptions` that gets used for my queries to have the rest of its configuration provided by the auto-configuration that's done in the `spring-cloud-gcp` project (specifically, in the `GcpSpannerAutoConfiguration` class).

I don't know what the best approach would be, but maybe it could involve exposing a `SpannerOptions.Builder` that's had its initial configuration done through the existing Spring auto-configuration, but that I could then configure further.

**Describe alternatives you've considered**

I've considered autowiring my own `SpannerOptions` bean in my app, to completely supersede the auto-configured one:

```java
	@Bean
	public SpannerOptions spannerOptions(SessionPoolOptions sessionPoolOptions) {
		// build a SpannerOptions from scratch and return it
	}
```

But, at least with my limited Spring experience, this would require somehow reproducing the logic and configuration that's done in `GcpSpannerAutoConfiguration` to set the projectId, credentials, etc. And even if I found a reasonable way to do that, this bean might now be at risk of diverging from any changes to the auto-configuration provided by future versions of this project.

If there's already a way to do this cleanly, I'd love to know.

**Additional context**

Probably not relevant, but I'm actually using Kotlin, not Java.

**Comment by elefeint** [comment]
There are workarounds such as custom bean post-processors, but ultimately the right solution is for this project to give you enough flexibility. We'd backport it to the old repo either way.

I see two reasonable solutions:
1) For us to introduce an optional `RetrySettings` bean that you could override. Since we don't specify any retry settings for Cloud Spanner, it would be safe for you to override this entire bean. **Pros**: simple. **Cons**: only works for retry settings, and we'll need to do the same when someone has to customize a part of the settings that we have not isolated in a bean yet.
2) Introduce a generic `ServiceOptionsCustomizer` (or more specific `SpannerOptionsCustomizer`) that would look for customizer beans and feed them an options/builder object to customize. **Pros**: covers all customization needs. **Cons**: more complicated to implement, requires developers to Learn Another Thing, and order of customizers will eventually need to be implemented.

Leaning towards the simplest solution here with (1). @meltsufin What do you think?

**Comment by joshrai** [comment]
Thanks so much, @elefeint . That all makes sense to me. I could see option 1 potentially complicating later efforts if option 2 were to become more compelling someday, but there would probably be ways for the two options to coexist for a while.

**Comment by joshrai** [comment]
I guess one other potential consideration is that some developers might want even finer control to use multiple `SpannerOptions` configurations within one app; in theory, if one were just using the Spanner client library directly, one would be able to tune the retry/timeout settings individually for each query being issued, based on arbitrary application logic. This isn't an immediate need for me, and I'm more than happy to keep it out of scope for this feature request, but I mention it in case it impacts your thinking about the direction to take.
