### ISSUE TITLE
SpannerTemplate should add query execution time in ApplicationEvents

### ISSUE THREAD

**Issue by pravsingh** [GoogleCloudPlatform/spring-cloud-gcp#520]
**Is your feature request related to a problem? Please describe.**
I'm capturing the ApplicationEvent. It has everything I need however missing the actual query execution times. Having this valuable information will help us monitor the queries better in our system.

**Describe the solution you'd like**
We are already capturing the timing in lower level methods e.g. executeRead. We could just pass it to the ApplicationEvent classes.

**Describe alternatives you've considered**
We tried abstracting out SpannerTemplate and measure the timings at this level however its another indirection which we would like to avoid and instead use the SpannerTemplate.

**Additional context**
N/A

**_In case you need developers, I can contribute as well._**

**Comment by mpeddada1** [comment]
Hi @pravsingh, thanks for filing this feature request! To clarify, are you aiming to store the execution time in an event (presumably an "after-{action}" event)?

**Comment by pravsingh** [comment]
yes.

**Comment by mpeddada1** [comment]
We would be happy to review your PR if you want to make a contribution!

**Comment by elefeint** [comment]
Closing the issue since nobody else expressed interest in the timing feature being added to Spanner events, and measuring timing before/after specific `PubSubTemplate` calls will result in essentially the same timing. It might make more sense to expose built-in Spanner query statistics (#598), but nobody seemed interested in that either.
