### ISSUE TITLE
reduce duplicated dependencies in samples

### ISSUE THREAD

**Issue by zhumin8** [GoogleCloudPlatform/spring-cloud-gcp#532]
We have a lot of repeating dependencies of commons-io in various samples. 
It would be beneficial to bring them in from one source. 

refer to this PR for details.
#529 
```
spring-cloud-gcp-autoconfigure/pom.xml
         <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.11.0</version>
            <scope>test</scope>
        </dependency>

spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/pom.xml
```

**Comment by zhumin8** [comment]
test comment.

**Comment by elefeint** [comment]
We've discussed it with @meltsufin when it came up for a dependabot upgrade. [The conclusion](https://github.com/spring-cloud/spring-cloud-gcp/pull/2672#discussion_r673409183) was that because users run our samples one at a time, each sample needs to be perfectly disconnectable from the samples parent.

So, works as intended.
