### ISSUE TITLE
[Spanner Data] Programmatic transaction handling causes nested transaction exception using 2 different repositories

### ISSUE THREAD

**Issue by sebarthel89** [GoogleCloudPlatform/spring-cloud-gcp#579]
**Describe the bug**
We would like to use provided spanner repositories and write changes to two tables in a single transaction. Unfortunately, this results in a Nested transaction executing to save method calls of two different repositories within a single readWrite transaction.

**Sample**
```
    // Open a single transaction
    this.traderRepository.performReadWriteTransaction(transactionTradeRepository -> {

      // save a trader
      transactionTraderRepository.save(new Trader("demo_trader1", "John", "Doe"));

      // save a trade
      // this causes a com.google.cloud.spanner.SpannerException: INTERNAL: Nested transactions are not supported
      this.tradeRepository
          .save(new Trade("1", "BUY", 100.0, 50.0, "STOCK1", "demo_trader1",
              Arrays.asList(99.0, 101.00)));

      return null;
    });
```

executable example: https://github.com/sebarthel89/spanner-data-example-nested-transaction-issue-combining-different-repositories

We would like to use the programmatic approach of opening transactions. It would be helpful to get an example or to fix it in case this is a bug.

This might be related to: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/568

Thanks in advance

**Comment by suztomo** [comment]
I'm checking the constraints on Spanner transaction. Give me some time.

**Comment by elefeint** [comment]
@sebarthel89 Thank you for the detailed reproducer example. `performReadWriteTransaction()` methods were meant to simplify transactional logic scoped to the same repository/template.

For the cross-repository transaction management, you have several good options:
1) Use any of the built-in Spring approaches for [programmatic transaction management](https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#transaction-programmatic).
For example, to use `TransactionTemplate`, you'd acquire the object from Spring context (it will automatically use Spanner transaction manager under the hood):
  ```
  @Autowired
  private TransactionTemplate springTransactionTemplate;
  ```
  And then the following will work as expected:
  ```
    springTransactionTemplate.execute(transactionStatus -> {
      this.traderRepository.save(new Trader("demo_trader1", "John", "Doe"));
      this.tradeRepository
          .save(new Trade("1", "BUY", 100.0, 50.0, "STOCK1", "demo_trader1",
              Arrays.asList(99.0, 101.00)));

      return null;
    });
  ```

2. Use declarative transactions (listed for completeness; I know you said that programmatic approach was preferable). For this to work, you need to make sure the[ method annotated as `@Transactional` is public](https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#transaction-declarative-annotations-method-visibility) and that `@EnableTransactionManagement` annotation is present on some `@Component` class in your application.

By the way, your example has a `@Transactional` annotation that's either unnecessary (because you are doing programmatic transaction management) or a no-op (because the method is not public and no `@EnableTransactionManagement` annotation is present in the app.

@suztomo thank you for bringing the issue up; we should document the use of Spring transaction management for more complex scenarios.

**Comment by sebarthel89** [comment]
very helpful! I will give it a try

**Comment by sebarthel89** [comment]
Works like a charm, thank you!

**Comment by YashJainSC** [comment]
@elefeint Is there any documentation on how to use declarative transactions for spanner ? Do we need to define bean for spannerTransactionManager or is it created automatically ?
