### ISSUE TITLE
Huge amount of ScheduledFutureTask in memory in case pubsub.googleapis.com isn't available

### ISSUE THREAD

**Issue by AcridFantasy** [GoogleCloudPlatform/spring-cloud-gcp#614]
**Describe the bug**
If pubsub.googleapis.com isn't available, there is a huge amount of _io.grpc.netty.shaded.io.netty.util.concurrent.ScheduledFutureTask_ objects instantiated (millions) that uses a huge amount of memory and can cause OOM and our service outage. Issue should be reproduced within 10 minutes after application is started. Prerequisite for this issue is that pubsub.googleapis.com isn't available. Originally it has been found in our docker environment, but I was able to reproduce it by simply adding this line to my **/etc/hosts** file:
**127.0.0.2 pubsub.googleapis.com**
Also, in our case, even full GC doesn't cleanup a lot of objects. For some reason, it is different for the sample project but it anyway causes OutOfMemoryError after some time.
This case is quite important for us because it can cause service outage (due to OOM) for all our service instances using PubSub. Fortunately, DNS failure happens rarely but still, it can happen and affect a lot of our users.

Screenshots from **VisualVM** tool are attached.
![total_objects_sample](https://user-images.githubusercontent.com/9916010/133094835-68ebc929-caec-4f27-bd37-fb7be74ae959.jpeg)
![heap_and_gc_activity](https://user-images.githubusercontent.com/9916010/133094847-4d09f146-6ce6-4ad2-b78f-3335dbe14981.jpeg)
![per_thread_allocation](https://user-images.githubusercontent.com/9916010/133094849-70d57a2e-b8ef-4a23-9026-b4eca48c9da3.jpeg)

**Sample**
I attached zip archive with the simple project reproducing the issue. Simply import it to your IDE and run main method in com.example.gcp_report.Main.kt file. Please don't forget to update your hosts as I mentioned above before run.
Sample prpject is here: https://github.com/AcridFantasy/gcp-memory-leak-report

Please let me know if there are any questions.

**Comment by elefeint** [comment]
Thank you for the detailed report; I will look to reproduce this week.

**Comment by elefeint** [comment]
@AcridFantasy Two months later... Apologies for not getting to this sooner.

There are two issues at hand -- how to make your application behave better, and how to stop uncontrollable spawning of Futures.

1) For your immediate (well, probably not immediate anymore) need, the solution is to set smaller timeout values. The timeouts in your example are all set to be 1 hour, while the polling is set to be every minute. So every minute, a task is started that will not complete for the next hour. You should allow the internal layers of Pub/Sub client library to fail after a timeout on the order of seconds or minutes, not hours, and definitely smaller than the `pollIntervalMs`. Instead of never timing out gRPC calls, overall application behavior can be controlled through the Reactor retry operators chained to `pubSubReactiveFactory.poll(subscriptionName, pollIntervalMs)`.

2) With that said, the issue you brought up is real -- we should not be spawning futures uncontrollably. At 1-2 futures (1 original and 1 retry) created every minute for an hour, memory should not get exhausted. I will investigate some more and file an issue with likely our Gax retry library.

Minimum reproduction case:
```
public class InfiniteFuturesTest {
	static String PROJECT_ID = "...";
	static String SUBSCRIPTION_NAME = "...";

	String subscriptionName = ProjectSubscriptionName.format(PROJECT_ID, SUBSCRIPTION_NAME);
	PullRequest pullRequest = PullRequest.newBuilder()
			.setMaxMessages(10)
			.setSubscription(subscriptionName)
			.build();

	SubscriberStubSettings.Builder settingsBuilder = SubscriberStubSettings
			.newBuilder()
			.setEndpoint("this.will.fail:443");

	@Test
	@Timeout(value = 10, unit = TimeUnit.MINUTES)
	void futuresBehaveWellWhenAllowedToFail() throws IOException {

		RetrySettings retryAllowedToFail = RetrySettings.newBuilder()
				.setInitialRpcTimeout(Duration.ofSeconds(5))
				.setMaxRpcTimeout(Duration.ofSeconds(5))
				.setMaxRetryDelay(Duration.ofSeconds(5))
				.setTotalTimeout(Duration.ofSeconds(5))
				.build();
		settingsBuilder.pullSettings().setRetrySettings(retryAllowedToFail);
		SubscriberStubSettings settings = settingsBuilder.build();

		try (SubscriberStub subscriber = GrpcSubscriberStub.create(settings)) {
			PullResponse pullResponse = subscriber.pullCallable().call(pullRequest);
			System.out.println("*** This should never happen, but okay: received "
					+ pullResponse.getReceivedMessagesCount() + " messages");
		} catch (Exception e) {
			System.out.println("*** Failed properly");
		}
	}

	@Test
	@Timeout(value = 10, unit = TimeUnit.MINUTES)
	void futuresNeverResolveWhenNotAllowedToFail() throws IOException {

		RetrySettings retryAllowedToFail = RetrySettings.newBuilder()
				.setInitialRpcTimeout(Duration.ofSeconds(3600))
				.setMaxRpcTimeout(Duration.ofSeconds(3600))
				.setMaxRetryDelay(Duration.ofSeconds(3600))
				.setTotalTimeout(Duration.ofSeconds(3600))
				.build();
		settingsBuilder.pullSettings().setRetrySettings(retryAllowedToFail);
		SubscriberStubSettings settings = settingsBuilder.build();

		try (SubscriberStub subscriber = GrpcSubscriberStub.create(settings)) {
			PullResponse pullResponse = subscriber.pullCallable().call(pullRequest);
			System.out.println("*** This should never happen, but okay: received "
					+ pullResponse.getReceivedMessagesCount() + " messages");
		} catch (Exception e) {
			System.out.println("*** Failed properly");
		}
	}
}
```

**Comment by AcridFantasy** [comment]
@elefeint thanks for the investigation and detailed report. 

No worries, there is no urgency. It's only reproducible on our QA env. 

From our side, there is no more questions, so this issue can be closed. 

Thanks! :)
