### ISSUE TITLE
Implement `getPersistentEntityTypeInformation()` and `getAssociationTargetTypeInformation()` in `SpannerCompositeKeyProperty`

### ISSUE THREAD

**Issue by zhumin8** [GoogleCloudPlatform/spring-cloud-gcp#656]
spring-data-commons-2.6.0-M3 [Consolidate names of methods that provide access to TypeInformation and Class on PersistentProperty](https://github.com/spring-projects/spring-data-commons/commit/e565c11dccda9f53cc4435e261d0c1ac62cfe9f1)

Need to implement additional methods in `SpannerCompositeKeyProperty` to be compatible with Spring Boot 2.6.

Error message:
```
Class 'SpannerCompositeKeyProperty' must either be declared abstract or implement abstract method 'getPersistentEntityTypeInformation()' in 'PersistentProperty'
Class 'SpannerCompositeKeyProperty' must either be declared abstract or implement abstract method 'getAssociationTargetTypeInformation()' in 'PersistentProperty'
```

This issue is derived from #599 .

**Comment by elefeint** [comment]
https://github.com/spring-projects/spring-data-commons/pull/2410

In case of Spanner, when column is known not to be an association, `getAssociationTargetTypeInformation` should simply return null.
`FirestorePersistentPropertyImpl` and `AnnotationBasedPersistentProperty` not affected because it extends `AnnotationBasedPersistentProperty`, which supplies an implementation of these. We should look at the functionality to check why Spanner could not use the standard annotations; probably because it's heavily custom.
