### ISSUE TITLE
Does Transactional RollbackFor supported in Datastore ?

### ISSUE THREAD

**Issue by beunick** [GoogleCloudPlatform/spring-cloud-gcp#907]
I have a method in my service like this

`@Transactional(rollbackFor = { ExceptionCanBeThrow.class })
public Something method() throws ExceptionCanBeThrow {
   // Logic to write in the DB
   // Logic that might thrown the exception.
}`

The problem is when the exception is raised and handle the rollback to the Datastore is not working.  The data is commit in datastore. 
I wonder if the Rollback is supported ? If yes any example how to properly do it with spring cloud datastore ?

Thanks for any help.

**Comment by elefeint** [comment]
Does rollback work for the general case, without `rollbackFor` specified?
Do you have `@EnableTransactionManagement` annotation in the application?

There is a [sample application](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/v3.0.0/spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample) showing how transactions work in Datastore. We never tested a specific exception type triggering a rollback, although this feels like it ought to be a built-in Spring detail that should not be affected by Datastore implementation.

**Comment by beunick** [comment]
@elefeint thanks for the note. 
I am not sure if this framework support all the requirement of the transaction of Spring. 
When for example I have a scenario of Transaction Propagation meaning:  a method with @transactional which called another method with @transactional, I received an error message like:

**"Participating in existing transactions is not supported - when 'isExistingTransaction' returns true, appropriate 'doSetRollbackOnly' behavior must be provided.**

What are the limitation of this spring-cloud-gcp -datastore in term of Transactions ? I went through your Document and it wasn't clear.  Do you support Transaction Propagation ?

Please help. 
Thanks

**Comment by elefeint** [comment]
This error message comes from Spring. It sounds like you are trying to set rollback behavior on only a child transaction -- while transaction propagation is supported (see [docs](https://googlecloudplatform.github.io/spring-cloud-gcp/3.0.0/reference/html/index.html#declarative-transactions-with-transactional-annotation-2), rolling back child transaction is not. 

We are happy to accept contributions that make the documentation more intuitive. The relevant part is "DatastoreTemplate and DatastoreRepository support running methods with the @Transactional annotation as transactions. If a method annotated with @Transactional calls another method also annotated, then both methods will work within the same transaction. performTransaction cannot be used in @Transactional annotated methods because Cloud Datastore does not support transactions within transactions."

**Comment by zhumin8** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
